"""init

Revision ID: ed8b276b4b27
Revises: 
Create Date: 2024-10-03 17:08:30.776259

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ed8b276b4b27'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdf_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('page_width', sa.Float(), nullable=False),
    sa.Column('created_stamp', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('text_box_coordinates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pdf_id', sa.Uuid(), nullable=False),
    sa.Column('x_coordinate', sa.Float(), nullable=False),
    sa.Column('y_coordinate', sa.Float(), nullable=False),
    sa.Column('box_width', sa.Float(), nullable=False),
    sa.Column('box_height', sa.Float(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_stamp', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_text_box_coordinates_id'), 'text_box_coordinates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_text_box_coordinates_id'), table_name='text_box_coordinates')
    op.drop_table('text_box_coordinates')
    op.drop_table('pdf_files')
    # ### end Alembic commands ###